export class Story {
    id?: number = 0;
    author: string = '';
    author_pic: string = '';
    cover: string = '';
    title: string = '';
    description: string = '';
    category: string = '';
    genre: string = '';
    tagged: string = '';
    uploaded: string = '';
    first_published: string = '';
    last_updated: string = '';
    status: string = '';
    pin: string = '';
    words: number = 0;
    comments: number = 0;
    chaps: number = 0;
}
